import type { ExtractionEvidence, ExtractionFieldDefinition, ExtractionFieldValue, ExtractionMethod, ExtractionRecord, ExtractionSchema, ExtractionSourceReference, JsonValue } from "./types";
import { EXTRACTION_LIMITS } from "./types";
import { normalizeExtractionValue, detectCurrency } from "./normalize";

export interface ExtractionTextSource { readonly documentId: string; readonly documentName: string; readonly sourceId: string; readonly sourceType: "native-text" | "ocr" | "office-text" | "office-cell" | "image"; readonly pageNumber?: number | null; readonly slideNumber?: number | null; readonly sheetName?: string | null; readonly cellRange?: string | null; readonly text: string; }

function labelPattern(field: ExtractionFieldDefinition): RegExp { const aliases = [field.label, field.id.replace(/[A-Z]/g, (letter) => ` ${letter.toLowerCase()}`), field.id]; const escaped = aliases.map((item) => item.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|"); return new RegExp(`(?:^|\\n|\\r)\\s*(?:${escaped})\\s*[:#-]\\s*(.+?)(?=\\n|\\r|$)`, "i"); }
function evidenceFor(source: ExtractionTextSource, fieldId: string, excerpt: string, startOffset: number): ExtractionEvidence { const bounded = excerpt.slice(0, EXTRACTION_LIMITS.maxEvidenceExcerpt); return { evidenceId: `${source.documentId}:${source.sourceId}:${fieldId}:${startOffset}`, documentId: source.documentId, sourceType: source.sourceType, sourceId: source.sourceId, pageNumber: source.pageNumber ?? null, slideNumber: source.slideNumber ?? null, sheetName: source.sheetName ?? null, cellRange: source.cellRange ?? null, textExcerpt: bounded, startOffset, endOffset: startOffset + bounded.length, boundingBox: null, extractionMethod: source.sourceType === "ocr" ? "ocr" : source.sourceType === "image" ? "inferred" : "native-text" }; }
function refFor(source: ExtractionTextSource, evidenceId: string): ExtractionSourceReference { return { documentId: source.documentId, documentName: source.documentName, evidenceIds: [evidenceId] }; }
function warning(code: "missing-required-field" | "weak-pattern" | "ambiguous-date" | "invalid-value", message: string, fieldId: string | null): ExtractionFieldValue["warnings"][number] { return { code, message, fieldId, severity: code === "invalid-value" ? "error" : "warning" }; }
function valueFromMatch(field: ExtractionFieldDefinition, source: ExtractionTextSource, match: RegExpExecArray): ExtractionFieldValue { const rawValue = match[1].trim(); const normalized = normalizeExtractionValue(rawValue, field); const evidence = evidenceFor(source, field.id, match[0], match.index); const method: ExtractionMethod = source.sourceType === "ocr" ? "ocr" : "deterministic"; const status = normalized.status === "normalized" ? "validated" : normalized.status === "invalid" ? "invalid" : "unknown"; const warnings = normalized.warning ? [warning(normalized.warning.includes("ambiguous") ? "ambiguous-date" : normalized.status === "invalid" ? "invalid-value" : "weak-pattern", normalized.warning, field.id)] : []; return { fieldId: field.id, value: (normalized.value ?? rawValue) as JsonValue, normalizedValue: normalized.value, rawValue, status, confidence: status === "validated" ? "high" : "low", confidenceScore: status === "validated" ? (method === "ocr" ? 0.86 : 0.96) : null, method, sourceReferences: [refFor(source, evidence.evidenceId)], evidence: [evidence], warnings }; }
function missingValue(field: ExtractionFieldDefinition): ExtractionFieldValue { return { fieldId: field.id, value: null, normalizedValue: null, rawValue: null, status: field.required ? "missing" : "unknown", confidence: "unknown", confidenceScore: null, method: null, sourceReferences: [], evidence: [], warnings: field.required ? [warning("missing-required-field", `${field.label} was not found in the bounded source text.`, field.id)] : [] }; }
function searchField(field: ExtractionFieldDefinition, sources: readonly ExtractionTextSource[]): ExtractionFieldValue { for (const source of sources) { const match = labelPattern(field).exec(source.text); if (match) return valueFromMatch(field, source, match); } if (field.id === "currency") { for (const source of sources) { const code = detectCurrency(source.text); if (code) { const index = source.text.indexOf(code); const evidence = evidenceFor(source, field.id, source.text.slice(Math.max(0, index - 18), index + 18), index); return { fieldId: field.id, value: code, normalizedValue: code, rawValue: code, status: "validated", confidence: "medium", confidenceScore: 0.78, method: "deterministic", sourceReferences: [refFor(source, evidence.evidenceId)], evidence: [evidence], warnings: [] }; } } } return missingValue(field); }
function extractRows(field: ExtractionFieldDefinition, sources: readonly ExtractionTextSource[]): ExtractionFieldValue { const rows: JsonValue[] = []; const evidence: ExtractionEvidence[] = []; for (const source of sources) { for (const line of source.text.split(/\r?\n/)) { const parts = line.split(/\s{2,}|\t|\s+\|\s+/).map((part) => part.trim()).filter(Boolean); if (parts.length < 2 || /^description\b/i.test(parts[0])) continue; const item: { [key: string]: JsonValue } = {}; field.itemFields?.forEach((child, index) => { if (parts[index]) item[child.id] = normalizeExtractionValue(parts[index], child).value ?? parts[index]; }); if (Object.keys(item).length > 0) { rows.push(item); const start = source.text.indexOf(line); evidence.push(evidenceFor(source, field.id, line, start < 0 ? 0 : start)); } if (rows.length >= EXTRACTION_LIMITS.maxRecords) break; } } return { fieldId: field.id, value: rows, normalizedValue: rows, rawValue: null, status: rows.length ? "validated" : "unknown", confidence: rows.length ? "medium" : "unknown", confidenceScore: rows.length ? 0.78 : null, method: rows.length ? "deterministic" : null, sourceReferences: evidence.map((item) => refFor(sources.find((source) => source.sourceId === item.sourceId) ?? sources[0], item.evidenceId)), evidence: evidence.slice(0, EXTRACTION_LIMITS.maxEvidencePerField), warnings: [] }; }

export function extractRecord(schema: ExtractionSchema, sources: readonly ExtractionTextSource[]): ExtractionRecord { const fields = schema.fields.slice(0, EXTRACTION_LIMITS.maxFields).map((field) => field.type === "table" || field.type === "array" ? extractRows(field, sources) : searchField(field, sources)); const present = fields.filter((field) => field.status === "validated" || field.status === "extracted" || field.status === "normalized").length; const requiredMissing = fields.filter((field) => field.status === "missing"); const warnings = fields.flatMap((field) => field.warnings); return { recordId: `${sources[0]?.documentId ?? "unknown"}:${schema.schemaId}`, documentId: sources[0]?.documentId ?? "unknown", documentName: sources[0]?.documentName ?? "Unknown document", schemaId: schema.schemaId, fields, status: requiredMissing.length > 0 ? "missing" : warnings.some((item) => item.severity === "error") ? "invalid" : "validated", coverage: fields.length === 0 ? 0 : present / fields.length, warnings, conflicts: [] }; }
