import { EXTRACTION_CONTRACT_VERSION, type ExtractionDocumentType, type ExtractionFieldDefinition, type ExtractionFieldType, type ExtractionSchema } from "./types";

const trim = (id = "trim"): ExtractionFieldDefinition["normalizationRules"] => [{ id, description: "Trim surrounding whitespace.", kind: "trim", parameters: {} }];
const required = (id: string, label: string, type: ExtractionFieldType, description: string, rules: ExtractionFieldDefinition["validationRules"] = []): ExtractionFieldDefinition => ({ id, label, type, required: true, nullable: false, description, normalizationRules: trim(), validationRules: [{ id: `${id}:required`, description: `${label} is required.`, kind: "required" }, ...rules], evidenceRequired: true });
const optional = (id: string, label: string, type: ExtractionFieldType, description: string): ExtractionFieldDefinition => ({ id, label, type, required: false, nullable: true, description, normalizationRules: trim(), validationRules: [], evidenceRequired: false });
const enumField = (id: string, label: string, values: readonly string[], description: string): ExtractionFieldDefinition => ({ ...optional(id, label, "enum", description), allowedValues: values, validationRules: [{ id: `${id}:enum`, description: `${label} must use an allowed value.`, kind: "enum", allowedValues: values }] });
const currency = (id: string, label: string, requiredField: boolean): ExtractionFieldDefinition => ({ ...(requiredField ? required(id, label, "currency", `${label} as a decimal monetary amount.`) : optional(id, label, "currency", `${label} as a decimal monetary amount.`)), normalizationRules: [{ id: `${id}:currency`, description: "Parse a decimal amount and preserve the detected currency separately when present.", kind: "currency", parameters: {} }] });
const date = (id: string, label: string, requiredField: boolean): ExtractionFieldDefinition => ({ ...(requiredField ? required(id, label, "date", `${label} in ISO-8601 form.`) : optional(id, label, "date", `${label} in ISO-8601 form.`)), normalizationRules: [{ id: `${id}:date`, description: "Normalize only unambiguous dates; retain ambiguous dates as unknown.", kind: "date", parameters: {} }] });
const baseInvoiceFields: readonly ExtractionFieldDefinition[] = [required("invoiceNumber", "Invoice number", "string", "Supplier-issued invoice identifier."), date("invoiceDate", "Invoice date", true), date("dueDate", "Due date", false), required("vendorName", "Vendor", "string", "Seller or issuer name."), optional("vendorEmail", "Vendor email", "email", "Seller contact email."), optional("customerName", "Customer", "string", "Buyer or recipient name."), optional("currency", "Currency", "string", "Detected currency code or symbol."), currency("subtotal", "Subtotal", false), currency("tax", "Tax", false), currency("total", "Total", true)];
const lineItems: ExtractionFieldDefinition = { id: "lineItems", label: "Line items", type: "table", required: false, nullable: true, description: "Bounded invoice line-item rows.", itemFields: [required("description", "Description", "string", "Line-item description."), optional("quantity", "Quantity", "number", "Line-item quantity."), currency("unitPrice", "Unit price", false), currency("amount", "Amount", false)], normalizationRules: [], validationRules: [], evidenceRequired: true };

function schema(schemaId: string, name: string, documentType: ExtractionDocumentType, description: string, fields: readonly ExtractionFieldDefinition[]): ExtractionSchema { return { schemaId, contractVersion: EXTRACTION_CONTRACT_VERSION, name, documentType, description, fields, maxDepth: 4, createdBy: "builtin" }; }

export const EXTRACTION_SCHEMAS: readonly ExtractionSchema[] = [
  schema("invoice-v1", "Invoice", "invoice", "Commercial invoice fields and bounded line items.", [...baseInvoiceFields, lineItems]),
  schema("receipt-v1", "Receipt", "receipt", "Retail receipt fields.", [required("merchantName", "Merchant", "string", "Merchant name."), date("purchaseDate", "Purchase date", false), currency("subtotal", "Subtotal", false), currency("tax", "Tax", false), currency("total", "Total", true), optional("paymentMethod", "Payment method", "string", "Payment method if shown."), optional("currency", "Currency", "string", "Detected currency code or symbol.")]),
  schema("contract-v1", "Contract", "contract", "Bounded contract parties, dates, and obligations.", [required("title", "Title", "string", "Contract title."), optional("partyA", "Party A", "string", "First named party."), optional("partyB", "Party B", "string", "Second named party."), date("effectiveDate", "Effective date", false), date("terminationDate", "Termination date", false), optional("governingLaw", "Governing law", "string", "Governing-law clause when explicitly present."), optional("renewalTerms", "Renewal terms", "string", "Renewal language when explicitly present.")]),
  schema("resume-v1", "Resume", "resume", "Candidate profile and employment signals.", [required("candidateName", "Candidate name", "string", "Candidate name."), optional("email", "Email", "email", "Candidate email."), optional("phone", "Phone", "phone", "Candidate phone."), optional("location", "Location", "string", "Candidate location."), optional("summary", "Summary", "string", "Profile summary."), { id: "skills", label: "Skills", type: "array", required: false, nullable: true, description: "Bounded skill labels.", normalizationRules: trim(), validationRules: [], evidenceRequired: false }, { id: "experience", label: "Experience", type: "table", required: false, nullable: true, description: "Bounded employment rows.", itemFields: [optional("employer", "Employer", "string", "Employer name."), optional("role", "Role", "string", "Role title."), date("startDate", "Start date", false), date("endDate", "End date", false)], normalizationRules: [], validationRules: [], evidenceRequired: false }]),
  schema("form-v1", "Form", "form", "Generic labeled form fields.", [optional("formTitle", "Form title", "string", "Visible form title."), { id: "fields", label: "Fields", type: "table", required: false, nullable: true, description: "Bounded label/value pairs.", itemFields: [required("label", "Label", "string", "Form label."), optional("value", "Value", "string", "Form value.")], normalizationRules: [], validationRules: [], evidenceRequired: true }]),
  schema("financial-document-v1", "Financial document", "financial-document", "Bounded financial statement signals.", [optional("accountName", "Account name", "string", "Account or entity name."), date("periodStart", "Period start", false), date("periodEnd", "Period end", false), currency("totalAssets", "Total assets", false), currency("totalLiabilities", "Total liabilities", false), currency("netIncome", "Net income", false), optional("currency", "Currency", "string", "Detected currency code or symbol.")]),
  schema("identity-document-signal-v1", "Identity document signals", "identity-document-signal", "Content signals only; does not verify identity authenticity.", [optional("documentNumber", "Document number", "string", "Visible document identifier, if present."), optional("personName", "Person name", "string", "Visible name, if present."), date("dateOfBirth", "Date of birth", false), date("expiryDate", "Expiry date", false), optional("issuingAuthority", "Issuing authority", "string", "Visible issuing authority."), enumField("documentSignal", "Document signal", ["content-present", "content-partial", "content-unreadable"], "Bounded content signal, not authenticity verification.")]),
  schema("purchase-order-v1", "Purchase order", "purchase-order", "Purchase-order identifiers, parties, and amounts.", [required("purchaseOrderNumber", "Purchase order number", "string", "Purchase-order identifier."), date("orderDate", "Order date", false), optional("supplierName", "Supplier", "string", "Supplier name."), optional("buyerName", "Buyer", "string", "Buyer name."), currency("subtotal", "Subtotal", false), currency("tax", "Tax", false), currency("total", "Total", false), lineItems]),
  schema("generic-document-v1", "Generic document", "generic-document", "Bounded labeled values and document signals.", [optional("title", "Title", "string", "Detected title."), optional("documentDate", "Document date", "date", "Detected document date."), { id: "keyValues", label: "Key/value fields", type: "table", required: false, nullable: true, description: "Bounded labeled values.", itemFields: [required("label", "Label", "string", "Value label."), optional("value", "Value", "string", "Value text.")], normalizationRules: [], validationRules: [], evidenceRequired: false }]),
];

export function getExtractionSchema(schemaId: string): ExtractionSchema | null { return EXTRACTION_SCHEMAS.find((item) => item.schemaId === schemaId) ?? null; }
export function getSchemaForDocumentType(documentType: ExtractionDocumentType): ExtractionSchema { return EXTRACTION_SCHEMAS.find((item) => item.documentType === documentType) ?? EXTRACTION_SCHEMAS[EXTRACTION_SCHEMAS.length - 1]; }
