export const PROJECT_CONTRACT_VERSION = "phase15-project-v1" as const;
export const PROJECT_LIMITS = { maxProjects: 50, maxDocumentsPerProject: 12, maxVersionsPerDocument: 20, maxWorkflowsPerProject: 100, maxHistoryEvents: 300, maxImportBytes: 2_000_000, maxNameLength: 120, maxDescriptionLength: 500 } as const;
export type ProjectStatus = "ACTIVE" | "ARCHIVED" | "DELETING" | "DELETED" | "RECOVERABLE" | "MIGRATION_REQUIRED" | "MIGRATION_FAILED";
export type ProjectDocumentStatus = "TEMPORARY" | "SAVED" | "PROCESSING" | "READY" | "INVALID" | "REPLACED" | "ARCHIVED" | "DELETED";
export type StorageRecordKind = "project" | "document" | "document-version" | "document-bytes" | "workflow" | "artifact" | "history" | "settings" | "migration";
export interface ProjectSettings { version: typeof PROJECT_CONTRACT_VERSION; localOnly: true; aiEnabled: boolean; retentionDays: number | null; keepOriginals: true; }
export interface StorageMetadata { version: typeof PROJECT_CONTRACT_VERSION; recordId: string; kind: StorageRecordKind; byteSize: number; createdAt: number; updatedAt: number; checksum: string | null; }
export interface DocumentVersion { version: typeof PROJECT_CONTRACT_VERSION; versionId: string; documentId: string; parentVersionId: string | null; sourceVersionId: string; artifactId: string; fileName: string; mimeType: string; sizeBytes: number; checksum: string | null; validationState: "validated" | "failed" | "unknown"; createdAt: number; originatingWorkflowId: string | null; originatingStepId: string | null; provenance: readonly string[]; warnings: readonly string[]; isOriginal: boolean; }
export interface ProjectDocument { version: typeof PROJECT_CONTRACT_VERSION; documentId: string; projectId: string; fileName: string; mimeType: string; sizeBytes: number; contentSignature: string; status: ProjectDocumentStatus; addedAt: number; updatedAt: number; versionIds: readonly string[]; activeVersionId: string; originalVersionId: string; validationState: "validated" | "failed" | "unknown"; sourceType: "image" | "pdf" | "office"; pageCount: number | null; }
export interface ProjectWorkflow { version: typeof PROJECT_CONTRACT_VERSION; workflowId: string; projectId: string; phase14SessionId: string | null; sourceDocumentIds: readonly string[]; checkpointIds: readonly string[]; retryCounts: Readonly<Record<string, number>>; reviewState: "none" | "open" | "approved" | "rejected"; qualityGateStatus: "pass" | "fail" | "warning" | "unknown"; reconciliationStatus: "none" | "consistent" | "warning" | "conflict" | "incomplete"; finalResultMetadata: readonly string[]; state: "planned" | "running" | "paused" | "recoverable" | "completed" | "partial" | "failed" | "cancelled"; createdAt: number; updatedAt: number; }
export interface ProjectArtifact { version: typeof PROJECT_CONTRACT_VERSION; artifactId: string; projectId: string; documentId: string | null; fileName: string | null; mimeType: string | null; sizeBytes: number | null; validationState: "validated" | "failed" | "unknown"; sourceWorkflowId: string | null; createdAt: number; }
export interface ProjectHistoryEvent { version: typeof PROJECT_CONTRACT_VERSION; eventId: string; projectId: string; type: "PROJECT_CREATED" | "PROJECT_UPDATED" | "DOCUMENT_SAVED" | "DOCUMENT_VERSION_CREATED" | "WORKFLOW_SAVED" | "WORKFLOW_RESUMED" | "WORKFLOW_COMPLETED" | "OUTPUT_RESTORED" | "PROJECT_ARCHIVED" | "PROJECT_DELETED" | "PROJECT_IMPORTED" | "PROJECT_EXPORTED"; metadata: Readonly<Record<string, string | number | boolean | null>>; createdAt: number; }
export interface RecoveryState { version: typeof PROJECT_CONTRACT_VERSION; interrupted: boolean; lastCheckpointId: string | null; completedCount: number; remainingCount: number; failedCount: number; reviewRequiredCount: number; }
export interface MigrationState { version: typeof PROJECT_CONTRACT_VERSION; schemaVersion: number; state: "current" | "required" | "running" | "failed"; message: string; updatedAt: number; }
export interface RetentionPolicy { version: typeof PROJECT_CONTRACT_VERSION; retainOriginals: true; retainValidatedVersions: true; removeFailedArtifactsAfterDays: number; removeDeletedProjectsAfterDays: number; }
export interface Project { version: typeof PROJECT_CONTRACT_VERSION; projectId: string; name: string; description: string; status: ProjectStatus; createdAt: number; updatedAt: number; documentCount: number; workflowCount: number; storageUsageBytes: number; settings: ProjectSettings; recovery: RecoveryState; migration: MigrationState; retention: RetentionPolicy; }
export interface StorageRecord<T> { metadata: StorageMetadata; value: T; }
export interface ExportPackage { version: typeof PROJECT_CONTRACT_VERSION; kind: "metadata" | "full"; project: Project; documents: readonly ProjectDocument[]; versions: readonly DocumentVersion[]; workflows: readonly ProjectWorkflow[]; artifacts: readonly ProjectArtifact[]; history: readonly ProjectHistoryEvent[]; includedBytes: boolean; createdAt: number; }
export interface ImportPackage extends ExportPackage { importId: string; checksum: string; trusted: false; }
export function stableProjectId(name: string, createdAt: number): string { return `project-${createdAt}-${name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 32) || "workspace"}`; }
export function validateProjectTransition(from: ProjectStatus, to: ProjectStatus): boolean { const transitions: Record<ProjectStatus, readonly ProjectStatus[]> = { ACTIVE: ["ARCHIVED", "DELETING", "MIGRATION_REQUIRED"], ARCHIVED: ["ACTIVE", "DELETING"], DELETING: ["DELETED", "RECOVERABLE"], DELETED: ["RECOVERABLE"], RECOVERABLE: ["ACTIVE", "DELETING"], MIGRATION_REQUIRED: ["ACTIVE", "MIGRATION_FAILED"], MIGRATION_FAILED: ["MIGRATION_REQUIRED"] }; return transitions[from].includes(to); }
export function validateProjectDocumentTransition(from: ProjectDocumentStatus, to: ProjectDocumentStatus): boolean { const transitions: Record<ProjectDocumentStatus, readonly ProjectDocumentStatus[]> = { TEMPORARY: ["SAVED", "INVALID"], SAVED: ["PROCESSING", "READY", "REPLACED", "ARCHIVED", "DELETED"], PROCESSING: ["READY", "INVALID", "SAVED"], READY: ["PROCESSING", "REPLACED", "ARCHIVED", "DELETED"], INVALID: ["SAVED", "DELETED"], REPLACED: ["READY", "ARCHIVED", "DELETED"], ARCHIVED: ["READY", "DELETED"], DELETED: [] }; return transitions[from].includes(to); }
