import type { ExtractionRecord } from "../extraction/types";
import { AUTOMATION_CONTRACT_VERSION, AUTOMATION_LIMITS, type AutomationDiscrepancy, type AutomationReconciliationResult } from "./types";

function field(record: ExtractionRecord, fieldId: string) { return record.fields.find((item) => item.fieldId === fieldId); }
function text(value: unknown): string { return typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : value === null || value === undefined ? "" : JSON.stringify(value); }
function normalized(value: string): string { return value.trim().toLowerCase().replace(/\s+/g, " "); }
function discrepancy(id: string, records: readonly ExtractionRecord[], fieldName: string, values: readonly string[], method: AutomationDiscrepancy["method"], message: string, severity: AutomationDiscrepancy["severity"]): AutomationDiscrepancy { return { version: AUTOMATION_CONTRACT_VERSION, discrepancyId: id, documentIds: records.map((record) => record.documentId), fieldNames: [fieldName], comparedValues: values, method, evidenceReferences: records.flatMap((record) => field(record, fieldName)?.evidence.map((evidence) => evidence.evidenceId) ?? []), severity, status: "open", message }; }
export function reconcileExtractionRecords(reconciliationId: string, records: readonly ExtractionRecord[], fieldNames: readonly string[], numericTolerance = 0.01): AutomationReconciliationResult { const bounded = records.slice(0, AUTOMATION_LIMITS.maxRecords); const discrepancies: AutomationDiscrepancy[] = []; const checkedFields: string[] = []; for (const fieldName of fieldNames.slice(0, 20)) { checkedFields.push(fieldName); const present = bounded.map((record) => ({ record, value: field(record, fieldName) })).filter((item) => item.value?.normalizedValue !== null && item.value?.normalizedValue !== undefined); if (present.length === 0) continue; if (present.length < bounded.length) discrepancies.push(discrepancy(`${reconciliationId}:missing:${fieldName}`, bounded, fieldName, present.map((item) => text(item.value?.normalizedValue)), "missing-counterpart", `Some documents do not contain a comparable ${fieldName}.`, "warning")); const values = present.map((item) => item.value?.normalizedValue ?? item.value?.value ?? null); const distinct = [...new Set(values.map((value) => normalized(text(value))))]; if (distinct.length > 1) { const numbers = values.map((value) => typeof value === "number" ? value : Number(value)).filter((value) => Number.isFinite(value)); const numericMatch = numbers.length === values.length && Math.max(...numbers) - Math.min(...numbers) <= numericTolerance; if (!numericMatch) discrepancies.push(discrepancy(`${reconciliationId}:conflict:${fieldName}`, present.map((item) => item.record), fieldName, values.map(text), fieldName.toLowerCase().includes("date") ? "date-normalization" : "normalized-equality", `Conflicting values were found for ${fieldName}; no winner was selected.`, "error")); } }
 const duplicateDocumentIds: string[] = []; const keys = new Map<string, string>(); for (const record of bounded) { const keyField = field(record, "invoiceNumber") ?? field(record, "purchaseOrderNumber") ?? field(record, "documentNumber"); const key = keyField?.normalizedValue === null || keyField?.normalizedValue === undefined ? "" : normalized(text(keyField.normalizedValue)); if (!key) continue; const previous = keys.get(key); if (previous && previous !== record.documentId) duplicateDocumentIds.push(record.documentId); else keys.set(key, record.documentId); } if (duplicateDocumentIds.length) discrepancies.push(discrepancy(`${reconciliationId}:duplicates`, bounded, "invoiceNumber", duplicateDocumentIds, "duplicate-key", "Repeated identifiers suggest duplicate documents; no record was removed.", "warning")); return { version: AUTOMATION_CONTRACT_VERSION, reconciliationId, documentIds: bounded.map((record) => record.documentId), discrepancies, duplicateDocumentIds: [...new Set(duplicateDocumentIds)], status: discrepancies.some((item) => item.severity === "error") ? "conflict" : discrepancies.length ? "warning" : bounded.length < 2 ? "incomplete" : "consistent", checkedFields }; }
