export const AUTOMATION_CONTRACT_VERSION = "phase14-automation-v1" as const;
export const AUTOMATION_LIMITS = { maxDocuments: 12, maxSteps: 100, maxRecords: 100, maxConcurrency: 2, maxAuditEvents: 300, maxCheckpoints: 40, maxWarnings: 100, maxEvidencePerField: 8, maxEvidenceExcerpt: 300, maxPackageArtifacts: 100 } as const;

export type AutomationSessionState = "draft" | "planned" | "review_required" | "running" | "paused" | "recoverable" | "completed" | "completed_with_warnings" | "partial" | "failed" | "cancelled";
export type AutomationStepStatus = "pending" | "running" | "success" | "failed" | "blocked" | "cancelled" | "skipped" | "waiting_review" | "retryable" | "validation_failed";
export type AutomationRecoveryStatus = "none" | "checkpoint_available" | "retryable_failure" | "needs_review" | "restored" | "abandoned";
export type AutomationReviewDecision = "approve" | "reject" | "modify" | "skip" | "retry";
export type AutomationQualityStatus = "pass" | "fail" | "warning" | "unknown" | "not_applicable";
export type AutomationAuditEventType = "DOCUMENT_ADDED" | "DOCUMENT_INSPECTED" | "WORKFLOW_PLANNED" | "WORKFLOW_REVIEWED" | "STEP_STARTED" | "STEP_COMPLETED" | "STEP_FAILED" | "STEP_RETRIED" | "VALIDATION_PASSED" | "VALIDATION_FAILED" | "REVIEW_REQUIRED" | "REVIEW_APPROVED" | "REVIEW_REJECTED" | "RECONCILIATION_COMPLETED" | "OUTPUT_CREATED" | "WORKFLOW_COMPLETED" | "WORKFLOW_CANCELLED";
export type AutomationComparisonMethod = "exact-equality" | "normalized-equality" | "numeric-tolerance" | "date-normalization" | "duplicate-key" | "missing-counterpart";
export type AutomationDiscrepancyStatus = "open" | "resolved" | "accepted" | "not-applicable";

export interface AutomationRetryPolicy { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly retryable: boolean; readonly maximumAttempts: number; readonly retryReason: string; readonly idempotency: "idempotent" | "best-effort" | "not-idempotent"; readonly backoff: "none" | "short" | "medium"; readonly automatic: boolean; }
export interface AutomationConfidenceThreshold { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly minimumCategory: "high" | "medium"; readonly minimumScore: number | null; readonly action: "continue" | "review"; }
export interface AutomationStepExecutionRecord { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly executionId: string; readonly stepId: string; readonly status: AutomationStepStatus; readonly attempt: number; readonly startedAt: number | null; readonly finishedAt: number | null; readonly retryPolicy: AutomationRetryPolicy; readonly message: string; readonly artifactIds: readonly string[]; readonly validationStatus: "pending" | "passed" | "failed" | "unknown"; readonly provenance: readonly string[]; }
export interface AutomationHumanReviewCheckpoint { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly checkpointId: string; readonly reason: string; readonly evidence: readonly string[]; readonly uncertainty: readonly string[]; readonly decisionRequired: string; readonly afterApproval: string; readonly decisions: readonly AutomationReviewDecision[]; readonly status: "open" | "approved" | "rejected" | "modified" | "skipped"; readonly createdAt: number; }
export interface AutomationWorkflowCheckpoint { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly checkpointId: string; readonly sessionId: string; readonly workflowId: string; readonly stepStates: Readonly<Record<string, AutomationStepStatus>>; readonly completedArtifactMetadata: readonly { readonly artifactId: string; readonly type: string; readonly byteSize: number | null; readonly validationStatus: string }[]; readonly validationStatus: "passed" | "failed" | "unknown"; readonly provenance: readonly string[]; readonly warnings: readonly string[]; readonly retryCounts: Readonly<Record<string, number>>; readonly humanReview: AutomationHumanReviewCheckpoint | null; readonly dependencyState: Readonly<Record<string, readonly string[]>>; readonly createdAt: number; }
export interface AutomationRecoveryState { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly state: "none" | "checkpoint_available" | "retryable_failure" | "needs_review" | "restored" | "abandoned"; readonly lastCheckpointId: string | null; readonly failedStepIds: readonly string[]; readonly message: string; }
export interface AutomationAuditEvent { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly eventId: string; readonly type: AutomationAuditEventType; readonly sessionId: string; readonly workflowId: string | null; readonly stepId: string | null; readonly documentIds: readonly string[]; readonly metadata: Readonly<Record<string, string | number | boolean | null>>; readonly timestamp: number; }
export interface AutomationQualityGate { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly gateId: string; readonly name: string; readonly required: boolean; readonly status: AutomationQualityStatus; readonly message: string; readonly checkedAt: number; }
export interface AutomationDiscrepancy { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly discrepancyId: string; readonly documentIds: readonly string[]; readonly fieldNames: readonly string[]; readonly comparedValues: readonly string[]; readonly method: AutomationComparisonMethod; readonly evidenceReferences: readonly string[]; readonly severity: "info" | "warning" | "error"; readonly status: AutomationDiscrepancyStatus; readonly message: string; }
export interface AutomationReconciliationResult { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly reconciliationId: string; readonly documentIds: readonly string[]; readonly discrepancies: readonly AutomationDiscrepancy[]; readonly duplicateDocumentIds: readonly string[]; readonly status: "consistent" | "warning" | "conflict" | "incomplete"; readonly checkedFields: readonly string[]; }
export interface AutomationEvidenceRecord { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly evidenceId: string; readonly documentId: string; readonly pageNumber: number | null; readonly sourceReference: string; readonly fieldId: string | null; readonly workflowStepId: string | null; readonly validationGateIds: readonly string[]; readonly excerpt: string; readonly method: "native-text" | "ocr" | "deterministic" | "ai" | "normalized" | "inferred"; }
export interface AutomationFinalDeliverable { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly deliverableId: string; readonly status: "verified" | "verified_with_warnings" | "needs_review" | "partial" | "failed" | "cancelled"; readonly workflowId: string; readonly artifactIds: readonly string[]; readonly qualityGates: readonly AutomationQualityGate[]; readonly reconciliation: AutomationReconciliationResult | null; readonly evidence: readonly AutomationEvidenceRecord[]; readonly warnings: readonly string[]; readonly createdAt: number; }
export interface AutomationPackageManifest { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly manifestId: string; readonly sessionId: string; readonly workflowId: string; readonly createdAt: number; readonly files: readonly { readonly artifactId: string; readonly fileName: string | null; readonly mimeType: string | null; readonly byteSize: number | null; readonly validationStatus: string }[]; readonly includesOriginalBytes: false; readonly includesRawPrompts: false; readonly includesApiKeys: false; readonly includesOcrImages: false; readonly deliverableId: string; }
export interface AutomationWorkflow { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly workflowId: string; readonly phase12WorkflowId: string; readonly goal: string; readonly stepIds: readonly string[]; readonly requiresHumanReview: boolean; readonly retryPolicies: Readonly<Record<string, AutomationRetryPolicy>>; readonly qualityGateIds: readonly string[]; readonly boundary: "browser-local" | "browser-local-to-ai-gateway"; }
export interface AutomationSession { readonly version: typeof AUTOMATION_CONTRACT_VERSION; readonly sessionId: string; readonly workflow: AutomationWorkflow; readonly state: AutomationSessionState; readonly recovery: AutomationRecoveryState; readonly stepRecords: readonly AutomationStepExecutionRecord[]; readonly checkpoints: readonly AutomationWorkflowCheckpoint[]; readonly reviews: readonly AutomationHumanReviewCheckpoint[]; readonly audit: readonly AutomationAuditEvent[]; readonly qualityGates: readonly AutomationQualityGate[]; readonly finalDeliverable: AutomationFinalDeliverable | null; readonly manifest: AutomationPackageManifest | null; readonly createdAt: number; readonly updatedAt: number; }
