import { useMemo, useState } from "react";
import { Check, ChevronRight, Download, FileJson, FileSpreadsheet, LockKeyhole, ShieldCheck, TriangleAlert } from "lucide-react";
import type { FileAsset } from "../../domain/files/types";
import { EXTRACTION_SCHEMAS, getSchemaForDocumentType } from "../../domain/extraction/schemas";
import { extractRecord, type ExtractionTextSource } from "../../domain/extraction/deterministic";
import { exportExtractionResult } from "../../domain/extraction/export";
import { validateExtractionRecord } from "../../domain/extraction/validation";
import type { ExtractionExportFormat, ExtractionFieldValue, ExtractionPlan, ExtractionSchema } from "../../domain/extraction/types";
import { planExtractionForAsset } from "./planner";
import { buildWorkflowPlan, type WorkflowPlan } from "../../domain/workflows/orchestration";

interface ExtractionWorkspaceProps { asset: FileAsset | null; onNavigateToPage?: (pageNumber: number) => void; }

export function ExtractionWorkspace({ asset, onNavigateToPage }: ExtractionWorkspaceProps) {
  const [goal, setGoal] = useState("Extract structured data from this document");
  const [schemaId, setSchemaId] = useState("generic-document-v1");
  const [sourceText, setSourceText] = useState("");
  const [plan, setPlan] = useState<{ extraction: ExtractionPlan; workflow: WorkflowPlan } | null>(null);
  const [record, setRecord] = useState<ReturnType<typeof extractRecord> | null>(null);
  const [selectedField, setSelectedField] = useState<ExtractionFieldValue | null>(null);
  const [exported, setExported] = useState<ReturnType<typeof exportExtractionResult> | null>(null);
  const [stage, setStage] = useState<"goal" | "schema" | "documents" | "plan" | "review" | "extract" | "validate" | "results" | "export">("goal");

  const selectedSchema = useMemo<ExtractionSchema>(() => EXTRACTION_SCHEMAS.find((schema) => schema.schemaId === schemaId) ?? getSchemaForDocumentType("generic-document"), [schemaId]);
  function reviewPlan() { if (!asset || !goal.trim()) return; const autoDetectSchema = schemaId === "generic-document-v1" && /invoice|bill|receipt|contract|agreement|resume|curriculum|purchase.?order|identity|passport|financial|balance sheet|income statement|form|application/i.test(goal); const next = planExtractionForAsset(asset, goal, autoDetectSchema ? undefined : selectedSchema); setPlan(next); setRecord(null); setExported(null); setStage("review"); }
  function extract() { if (!asset || !plan) return; setStage("extract"); const source: ExtractionTextSource = { documentId: asset.id, documentName: asset.name, sourceId: `${asset.id}:bounded-source`, sourceType: asset.category === "office" ? "office-text" : asset.category === "pdf" && asset.textExtractable ? "native-text" : asset.category === "image" ? "image" : "ocr", pageNumber: asset.category === "pdf" ? 1 : null, slideNumber: null, sheetName: null, cellRange: null, text: sourceText.slice(0, 120_000) }; const nextRecord = extractRecord(plan.extraction.schema, [source]); setRecord(nextRecord); setStage("validate"); setStage("results"); }
  function download(format: ExtractionExportFormat) { if (!record) return; const result = exportExtractionResult(record, format); setExported(result); if (!result.valid) return; const url = URL.createObjectURL(new Blob([result.content], { type: result.mimeType })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.fileName; anchor.click(); URL.revokeObjectURL(url); setStage("export"); }
  const validation = record && plan ? validateExtractionRecord(record, plan.extraction.schema, new Set([asset?.id ?? ""])) : null;
  if (!asset) return null;
  return <section className="extraction-workspace" aria-labelledby="extraction-workspace-title">
    <div className="extraction-heading"><div><p className="eyebrow"><span className="eyebrow-line" /> Phase 13 · Structured extraction</p><h3 id="extraction-workspace-title">Extract Data from your document.</h3><p>Turn bounded document evidence into reviewable structured records. Deterministic extraction runs first; AI remains optional and explicitly disclosed.</p></div><span className="local-badge"><ShieldCheck size={13} /> Originals stay local</span></div>
    <div className="extraction-stages" aria-label="Extraction workflow stages">{["goal", "schema", "documents", "plan", "review", "extract", "validate", "results", "export"].map((item, index) => <span key={item} className={stage === item ? "active" : index < ["goal", "schema", "documents", "plan", "review", "extract", "validate", "results", "export"].indexOf(stage) ? "done" : ""}>{index + 1} {item}</span>)}</div>
    <div className="extraction-grid">
      <div className="workflow-card extraction-input-card"><div className="card-label"><span className="label-icon violet"><FileJson size={15} /></span> 01 · Goal and schema</div><label className="goal-label" htmlFor="extraction-goal">What structured data should be extracted?</label><textarea id="extraction-goal" value={goal} onChange={(event) => { setGoal(event.target.value); setPlan(null); setRecord(null); }} rows={3} placeholder="e.g. extract invoice number, dates, vendor, currency, total, and line items" /><label className="goal-label" htmlFor="extraction-schema">Schema</label><select id="extraction-schema" value={schemaId} onChange={(event) => { setSchemaId(event.target.value); setPlan(null); setRecord(null); }}>{EXTRACTION_SCHEMAS.map((schema) => <option key={schema.schemaId} value={schema.schemaId}>{schema.name}</option>)}</select><p className="microcopy"><LockKeyhole size={12} /> {plan?.extraction.processingBoundary === "browser-local-to-ai-gateway" ? "AI-assisted plan requires explicit consent." : "Browser-local deterministic-first plan."}</p><button className="primary-button" type="button" onClick={reviewPlan}>Review extraction plan <ChevronRight size={15} /></button></div>
      <div className="workflow-card extraction-source-card"><div className="card-label"><span className="label-icon"><FileSpreadsheet size={15} /></span> 02 · Bounded source evidence</div><p className="source-document-name"><strong>{asset.name}</strong><span>{asset.category.toUpperCase()} · {asset.sizeBytes.toLocaleString()} bytes</span></p><label className="goal-label" htmlFor="extraction-source">Paste bounded text evidence for this review</label><textarea id="extraction-source" value={sourceText} onChange={(event) => setSourceText(event.target.value)} rows={8} placeholder={'Invoice Number: INV-2026-001\nInvoice Date: 2026-08-27\nVendor: Example Supplies\nTotal: ₹12,500'} /><p className="microcopy">The source text is bounded in memory. Full PDF bytes never cross an AI boundary.</p></div>
    </div>
    {plan ? <div className="extraction-plan-panel"><div className="graph-header"><p className="eyebrow">03 · Reviewable Phase 12 plan</p><span className="unified-risk risk-low">{plan.extraction.risk} risk</span></div><div className="extraction-step-row">{plan.workflow.steps.map((step, index) => <div key={step.id} className="extraction-step"><span>{index + 1}</span><strong>{step.capability.replaceAll("document.extract.", "")}</strong><small>{step.processingBoundary === "browser-local" ? "Local" : "AI Gateway"}</small></div>)}</div><div className="disclosure-grid"><div className="disclosure-item"><span>OCR required</span><strong>{plan.extraction.requiresOcr ? "Yes" : "No"}</strong></div><div className="disclosure-item"><span>AI required</span><strong>{plan.extraction.requiresAi ? "Yes" : "No"}</strong></div><div className="disclosure-item"><span>Fields in schema</span><strong>{plan.extraction.schema.fields.length}</strong></div><div className="disclosure-item"><span>Export formats</span><strong>JSON · CSV</strong></div></div>{plan.extraction.warnings.map((warning) => <p className="unified-warning" key={warning.message}><TriangleAlert size={14} /> {warning.message}</p>)}<button className="primary-button extraction-run-button" type="button" onClick={extract}><Check size={15} /> Extract and validate record</button></div> : null}
    {record && validation ? <div className="extraction-result-panel"><div className="result-heading"><div><p className="eyebrow">04 · Validated structured result</p><h3>{plan?.extraction.schema.name}</h3></div><span className={`history-state ${validation.valid ? "validated" : "warning"}`}>{validation.status}</span></div><div className="extraction-metrics"><div><span>Record status</span><strong>{record.status}</strong></div><div><span>Coverage</span><strong>{Math.round(record.coverage * 100)}%</strong></div><div><span>Warnings</span><strong>{validation.warnings.length}</strong></div><div><span>Conflicts</span><strong>{validation.conflicts.length}</strong></div></div><div className="field-list">{record.fields.map((field) => <button type="button" key={field.fieldId} className={`field-row ${selectedField?.fieldId === field.fieldId ? "selected" : ""}`} onClick={() => setSelectedField(field)}><span><strong>{plan?.extraction.schema.fields.find((definition) => definition.id === field.fieldId)?.label ?? field.fieldId}</strong><small>{field.status} · {field.confidence}</small></span><b>{field.normalizedValue === null ? "Unknown / missing" : JSON.stringify(field.normalizedValue)}</b></button>)}</div>{selectedField ? <div className="field-inspector"><p className="eyebrow">Field inspector</p><h4>{selectedField.fieldId}</h4><dl><div><dt>Value</dt><dd>{JSON.stringify(selectedField.value)}</dd></div><div><dt>Normalized</dt><dd>{JSON.stringify(selectedField.normalizedValue)}</dd></div><div><dt>Method</dt><dd>{selectedField.method ?? "Unknown"}</dd></div><div><dt>Confidence</dt><dd>{selectedField.confidence}</dd></div><div><dt>Evidence</dt><dd>{selectedField.evidence[0]?.textExcerpt ?? "No evidence reference"}</dd></div></dl>{selectedField.evidence[0]?.pageNumber ? <button className="secondary-button" type="button" onClick={() => onNavigateToPage?.(selectedField.evidence[0]?.pageNumber ?? 1)}>Open source page</button> : null}</div> : null}<div className="result-actions"><button className="secondary-button" type="button" onClick={() => download("json")}><Download size={14} /> Export JSON</button><button className="secondary-button" type="button" onClick={() => download("csv")}><Download size={14} /> Export CSV</button></div>{exported && !exported.valid ? <p className="unified-warning"><TriangleAlert size={14} /> {exported.warnings[0]?.message}</p> : null}</div> : null}
  </section>;
}
