import type { FileAsset } from "../../domain/files/types";
import { buildWorkflowPlan, createWorkflowStep, type WorkflowPlan, type WorkflowStep } from "../../domain/workflows/orchestration";
import { EXTRACTION_CONTRACT_VERSION, type ExtractionDocumentType, type ExtractionPlan, type ExtractionSchema } from "../../domain/extraction/types";
import { getSchemaForDocumentType } from "../../domain/extraction/schemas";

export interface ExtractionDocumentInput { readonly id: string; readonly name: string; readonly mimeType: string; readonly category: "image" | "pdf" | "office"; readonly textAvailable?: boolean; readonly scanned?: boolean; }
function stablePlanId(ids: readonly string[], goal: string): string { let hash = 2166136261; for (const character of `${ids.join("|")}|${goal.trim().toLowerCase()}|${EXTRACTION_CONTRACT_VERSION}`) hash = Math.imul(hash ^ character.charCodeAt(0), 16777619); return `extract-${(hash >>> 0).toString(36)}`; }
function typeFromGoal(goal: string, asset?: Pick<FileAsset, "category" | "name">): ExtractionDocumentType { const normalized = `${goal} ${asset?.name ?? ""}`.toLowerCase(); if (/invoice|bill/.test(normalized)) return "invoice"; if (/receipt/.test(normalized)) return "receipt"; if (/contract|agreement|terms/.test(normalized)) return "contract"; if (/resume|cv|curriculum/.test(normalized)) return "resume"; if (/purchase.?order|po number/.test(normalized)) return "purchase-order"; if (/identity|passport|driver|license|national id/.test(normalized)) return "identity-document-signal"; if (/financial|balance sheet|income statement/.test(normalized)) return "financial-document"; if (/form|application/.test(normalized)) return "form"; return "generic-document"; }
function step(id: string, capability: string, type: WorkflowStep["type"], documentIds: readonly string[], dependencies: readonly string[], schema: ExtractionSchema, boundary: WorkflowStep["processingBoundary"], risk: WorkflowStep["risk"] = "low", requiresConfirmation = false): WorkflowStep { return createWorkflowStep({ id, type, capability, inputs: documentIds.map((documentId) => ({ kind: "original-document", documentId, fileName: documentId, mimeType: "application/octet-stream" })), dependencies, expectedOutputs: [{ artifactId: `${id}:result`, type: capability.includes("export") ? "final-result" : capability.includes("validate") ? "analysis-result" : "intermediate-document", fileName: null, mimeType: null, terminal: capability.includes("export") }], risk, processingBoundary: boundary, validationPlan: [{ id: `${id}:validation`, description: capability.includes("provenance") ? "Validate all field evidence against supplied source references." : capability.includes("validate") ? "Validate schema, field types, required fields, and normalization results." : `Validate ${schema.name} extraction step output.`, required: true, status: "pending", message: null }], provenance: { sourceDocumentIds: documentIds, parentArtifactIds: [], originatingStepId: id, sourceType: capability.includes("ai") ? "ai-proposal" : "original", location: null, confidence: capability.includes("ai") ? "low" : "high" }, failurePolicy: documentIds.length > 1 ? "skip_failed_document" : "continue_best_effort", retryPolicy: capability.includes("ai") ? "bounded-retryable" : "never", cancellationPolicy: "cancellable", resourceClass: capability.includes("ocr") ? "ocr" : capability.includes("ai") ? "ai" : capability.includes("validate") ? "light" : "document", requiresConfirmation }); }

export function planExtractionForDocuments(documents: readonly ExtractionDocumentInput[], goal: string, schemaOverride?: ExtractionSchema): { readonly extraction: ExtractionPlan; readonly workflow: WorkflowPlan } {
  const documentIds = documents.map((document) => document.id);
  const first = documents[0];
  const documentType = schemaOverride?.documentType ?? typeFromGoal(goal, first ? { category: first.category, name: first.name } : undefined);
  const schema = schemaOverride ?? getSchemaForDocumentType(documentType);
  const allText = documents.every((document) => document.textAvailable !== false && document.category !== "image");
  const requiresOcr = documents.some((document) => document.scanned === true || (document.category === "image" && !document.textAvailable));
  const explicitAi = /\bai\b|semantic|interpret|ambiguous|understand relationships/.test(goal.toLowerCase());
  const requiresAi = explicitAi;
  const boundary: WorkflowStep["processingBoundary"] = requiresAi ? "browser-local-to-ai-gateway" : "browser-local";
  const planId = stablePlanId(documentIds, goal);
  const warnings = documentType === "identity-document-signal" ? [{ code: "unverified-identity" as const, message: "Identity-document signals describe visible content only and do not verify identity authenticity.", fieldId: null, severity: "warning" as const }] : [];
  const steps: WorkflowStep[] = [];
  const inspect = `${planId}:inspect`; steps.push(step(inspect, documentIds.length > 1 ? "document.extract.inspect.collection" : "document.extract.inspect", "inspect", documentIds, [], schema, "browser-local"));
  let previous = inspect;
  if (!allText) { const text = `${planId}:text`; steps.push(step(text, "document.extract.text", "analysis", documentIds, [previous], schema, "browser-local")); previous = text; }
  if (requiresOcr) { const ocr = `${planId}:ocr`; steps.push(step(ocr, "document.extract.ocr", "transform", documentIds, [previous], schema, "browser-local")); previous = ocr; }
  const deterministic = `${planId}:deterministic`; steps.push(step(deterministic, "document.extract.deterministic", documents.length > 1 ? "foreach" : "analysis", documentIds, [previous], schema, "browser-local")); previous = deterministic;
  if (requiresAi) { const ai = `${planId}:ai`; steps.push(step(ai, "document.extract.ai", "analysis", documentIds, [previous], schema, boundary, "medium", true)); previous = ai; }
  const normalize = `${planId}:normalize`; steps.push(step(normalize, "document.extract.normalize", "analysis", documentIds, [previous], schema, "browser-local")); previous = normalize;
  const validate = `${planId}:validate`; steps.push(step(validate, "document.extract.validate", "validate", documentIds, [previous], schema, "browser-local")); previous = validate;
  const provenance = `${planId}:provenance`; steps.push(step(provenance, "document.extract.provenance", "validate", documentIds, [previous], schema, "browser-local")); previous = provenance;
  if (documents.length > 1) { const aggregate = `${planId}:aggregate`; steps.push(step(aggregate, "document.extract.aggregate", "merge", documentIds, [previous], schema, "browser-local")); previous = aggregate; }
  const exportStep = `${planId}:export`; steps.push(step(exportStep, "document.extract.export", "transform", documentIds, [previous], schema, "browser-local"));
  const workflow = buildWorkflowPlan({ workflowId: planId, contractVersion: "phase12-workflow-v1", goal, steps, failurePolicy: documents.length > 1 ? "skip_failed_document" : "continue_best_effort", requiresConfirmation: requiresAi, processingBoundary: boundary, warnings: warnings.map((item) => item.message) });
  return { extraction: { planId, contractVersion: EXTRACTION_CONTRACT_VERSION, goal, schema, documentIds, documentType, requiresOcr, requiresTextExtraction: !allText, requiresAi, deterministicOpportunities: ["labeled key/value patterns", "dates", "amounts", "currency", "email", "phone", "URL", "bounded table rows"], normalizationRequirements: schema.fields.flatMap((field) => field.normalizationRules.map((rule) => rule.description)), validationRequirements: ["schema", "required fields", "field types", "source identity", "evidence", "normalized values"], provenanceRequirements: ["real document IDs", "page/slide/sheet references when available", "bounded evidence excerpts"], aggregationRules: documents.length > 1 ? [{ id: "count-records", fieldId: "record", operation: "count", outputFieldId: "aggregate.record.count" }] : [], exportFormats: ["json", "csv"], processingBoundary: boundary, risk: requiresAi ? "medium" : "low", warnings, workflowStepIds: steps.map((item) => item.id), valid: workflow.valid }, workflow }; }

export function planExtractionForAsset(asset: FileAsset, goal: string, schemaOverride?: ExtractionSchema): { readonly extraction: ExtractionPlan; readonly workflow: WorkflowPlan } { return planExtractionForDocuments([{ id: asset.id, name: asset.name, mimeType: asset.mimeType, category: asset.category, textAvailable: asset.category === "pdf" ? asset.textExtractable : asset.category === "office", scanned: asset.category === "pdf" ? asset.classification === "scanned" : false }], goal, schemaOverride); }
