from pathlib import Path

from fpdf import FPDF
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
ROOT.mkdir(parents=True, exist_ok=True)


def page_pdf(path: Path, pages: list[str], image_page: bool = False) -> None:
    pdf = FPDF()
    pdf.set_title(path.stem)
    pdf.set_author("SmartDocs fixture generator")
    for index, text in enumerate(pages):
        pdf.add_page()
        if image_page or (index == len(pages) - 1 and text == ""):
            pdf.image(str(ROOT / "scan-page.png"), x=15, y=28, w=180)
        else:
            pdf.set_font("Helvetica", size=16)
            pdf.cell(0, 10, text)
            pdf.ln(12)
            pdf.set_font("Helvetica", size=11)
            pdf.multi_cell(0, 6, "This is a reproducible SmartDocs fixture used for local PDF inspection tests.")
    pdf.output(str(path))


image = Image.new("RGB", (900, 1200), "white")
draw = ImageDraw.Draw(image)
draw.rectangle((30, 30, 870, 1170), outline=(25, 35, 75), width=8)
for y in range(80, 1120, 42):
    draw.line((90, y, 810, y), fill=(90, 100, 130), width=4)
draw.text((90, 560), "Scanned document fixture", fill=(25, 35, 75))
image.save(ROOT / "scan-page.png")

page_pdf(ROOT / "text-fixture.pdf", ["SmartDocs text PDF fixture", "Second text page"])
page_pdf(ROOT / "scanned-fixture.pdf", ["", ""], image_page=True)
page_pdf(ROOT / "mixed-fixture.pdf", ["SmartDocs mixed PDF fixture", "" ])
(ROOT / "invalid-fixture.pdf").write_bytes(b"this is not a PDF")
# Sparse repeated pages make an oversized input without private content.
page_pdf(ROOT / "oversized-fixture.pdf", [f"Oversized fixture page {index}" for index in range(80)])
with (ROOT / "fixtures.md").open("w", encoding="utf-8") as document:
    document.write("""# PDF fixtures\n\nGenerated by `python3 tests/fixtures/generate_pdf_fixtures.py`.\n\n- `text-fixture.pdf`: two text pages.\n- `scanned-fixture.pdf`: two image-only pages.\n- `mixed-fixture.pdf`: one text page and one image-only page.\n- `invalid-fixture.pdf`: deterministic non-PDF bytes.\n- `oversized-fixture.pdf`: reproducible multi-page input for size-limit handling; the browser test uses a synthetic size-boundary case rather than loading it if the generated file is below 50 MB.\n""")
