from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
ROOT.mkdir(parents=True, exist_ok=True)


def page_pdf(path: Path, pages: list[str], image_page: bool = False) -> None:
    pdf = FPDF()
    pdf.set_title(path.stem)
    pdf.set_author("SmartDocs fixture generator")
    pdf.creation_date = datetime(1969, 12, 31, 19, 0, tzinfo=timezone.utc)
    for index, text in enumerate(pages):
        pdf.add_page()
        if image_page or (index == len(pages) - 1 and text == ""):
            pdf.image(str(ROOT / "scan-page.png"), x=15, y=28, w=180)
        else:
            pdf.set_font("Helvetica", size=16)
            pdf.cell(0, 10, text)
            pdf.ln(12)
            pdf.set_font("Helvetica", size=11)
            pdf.multi_cell(0, 6, "This is a reproducible SmartDocs fixture used for local PDF inspection tests.")
    pdf.output(str(path))


image = Image.new("RGB", (900, 1200), "white")
draw = ImageDraw.Draw(image)
draw.rectangle((30, 30, 870, 1170), outline=(25, 35, 75), width=8)
for y in range(80, 1120, 42):
    draw.line((90, y, 810, y), fill=(90, 100, 130), width=4)
draw.text((90, 560), "Scanned document fixture", fill=(25, 35, 75))
image.save(ROOT / "scan-page.png")

page_pdf(ROOT / "text-fixture.pdf", ["SmartDocs text PDF fixture", "Second text page"])
page_pdf(ROOT / "scanned-fixture.pdf", ["", ""], image_page=True)
page_pdf(ROOT / "mixed-fixture.pdf", ["SmartDocs mixed PDF fixture", ""])
page_pdf(ROOT / "multipage-fixture.pdf", [f"Navigation fixture page {index}" for index in range(1, 13)])
page_pdf(ROOT / "sampling-fixture.pdf", [f"Sampling fixture page {index}" for index in range(1, 101)])
(ROOT / "invalid-fixture.pdf").write_bytes(b"this is not a PDF")
# Sparse repeated pages make an oversized input without private content.
page_pdf(ROOT / "oversized-fixture.pdf", [f"Oversized fixture page {index}" for index in range(80)])

(ROOT / "fixtures.md").write_text(
    """# PDF fixtures

Generated by `python3 tests/fixtures/generate_pdf_fixtures.py`.

- `text-fixture.pdf`: two text pages.
- `scanned-fixture.pdf`: two image-only pages.
- `mixed-fixture.pdf`: one text page and one image-only page.
- `multipage-fixture.pdf`: twelve text pages for navigation and thumbnails.
- `sampling-fixture.pdf`: one hundred text pages for bounded sampling behavior.
- `invalid-fixture.pdf`: deterministic non-PDF bytes.
- `oversized-fixture.pdf`: reproducible multi-page input for size-limit handling; the browser test uses a synthetic size-boundary case rather than loading it if the generated file is below 50 MB.
""",
    encoding="utf-8",
)
